config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  devise_for :users

  authenticate :user do
    mount Sidekiq::Web => "/sidekiq"
  end

  resources :citizens, except: [:destroy] do
    collection do
      get :data
      get :cities
    end
  end

  root "citizens#index"
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :citizen
  belongs_to :state
  belongs_to :city

  validates :zipcode, :street, :neighbourhood, presence: true
  validates_associated :state, :city

  before_validation do
    self.zipcode = zipcode&.scan(/[+\d]/)&.join("")
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/citizen.rb
class Citizen < ApplicationRecord
  has_one :address

  validates :name, :cpf, :cns, :phone, :birthdate, :photo, presence: true
  validates :phone, format: { with: /\A\+55\d{2}\d{9}\z/ }
  validates_email_format_of :email, disposable: true
  validates_cpf_format_of :cpf

  mount_uploader :photo, PhotoUploader

  accepts_nested_attributes_for :address

  scope :search, -> q do
    search = "%#{q}%"

    joins(:address).where("
      name ilike ? or phone ilike ? or email ilike ? or cpf ilike ? or cns ilike ?
      or addresses.zipcode ilike ? or addresses.street ilike ? or addresses.neighbourhood ilike ?
    ", search, search, search, search, search, search, search, search)
  end

  before_validation do
    self.phone = phone&.scan(/[+\d]/)&.join("")
    self.cpf = cpf&.scan(/\d/)&.join("")
  end
end

app/models/city.rb
class City < ApplicationRecord
  belongs_to :state

  validates :state_id, :name, presence: true
  validates_uniqueness_of :name, scope: :state_id
end

app/models/state.rb
class State < ApplicationRecord
  has_many :cities

  validates :name, :acronym, presence: true, uniqueness: true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/citizens_controller.rb
class CitizensController < ApplicationController
  def data
    @citizens = Citizen.search(search_params[:q]).decorate.collect { |c| [c.id, c.name, c.cpf, c.email] }

    render layout: false, partial: "components/table/rows", locals: { rows: @citizens }
  end

  def cities
    @cities = City.where(city_params).collect { |c| [c.name, c.id] }

    render layout: false,
           partial: "components/form/select",
           locals: {
             object_name: "citizen[address_attributes]",
             name: "city_id",
             collection: @cities,
             selected: nil,
             attrs: {}
           }
  end

  def new
    @citizen = Citizen.new
    @states = State.all.collect { |c| [c.name, c.id] }
    @cities = []
  end

  def create
    @citizen = Citizen.new(citizen_params)

    service = CitizenCreateService.new(@citizen)
    result = service.call

    if result[:success]
      redirect_to citizens_path, notice: t("messages.success.created")
    else
      @states = State.all.collect { |c| [c.name, c.id] }
      @cities = City.where(state_id: @citizen.address.state_id).collect { |c| [c.name, c.id] }

      render :new
    end
  end

  def show
    @citizen = Citizen.find(params[:id]).decorate
  end

  def edit
    @citizen = Citizen.find(params[:id]).decorate
    @states = State.all.collect { |c| [c.name, c.id] }
    @cities = City.where(state_id: @citizen.address.state_id).collect { |c| [c.name, c.id] }
  end

  def update
    @citizen = Citizen.find(params[:id])

    service = CitizenUpdateService.new(@citizen, citizen_params)
    result = service.call

    if result[:success]
      redirect_to citizens_path, notice: t("messages.success.saved")
    else
      @states = State.all.collect { |c| [c.name, c.id] }
      @cities = City.where(state_id: @citizen.address.state_id).collect { |c| [c.name, c.id] }

      render :edit
    end
  end

  private

  def citizen_params
    params.require(:citizen).permit(:name, :email, :cpf, :cns, :phone, :birthdate, :photo, :photo_cache, :active,
                                    address_attributes: [:id, :state_id, :city_id, :zipcode, :street, :neighbourhood,
                                                         :complement, :ibge_code])
  end

  def city_params
    params.permit(:state_id)
  end

  def search_params
    params.permit(:q)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def errors_for(f, field)
    f.object.errors[field].map do |error|
      tag.p(error, class: "text-red-700")
    end.join.html_safe
  end

  def color_classes(type)
    case type.to_sym
    when :success
      "bg-green-100 border-green-400 text-green-700"
    when :alert
      "bg-red-100 border-red-400 text-red-700"
    when :warning
      "bg-yellow-100 border-yellow-400 text-yellow-700"
    when :notice
      "bg-blue-100 border-blue-400 text-blue-700"
    else
      "bg-gray-100 border-gray-400 text-gray-700"
    end
  end
end

app/helpers/citizens_helper.rb
module CitizensHelper
  def headers
    [
      t("activerecord.attributes.citizen.id"),
      t("activerecord.attributes.citizen.name"),
      t("activerecord.attributes.citizen.cpf"),
      t("activerecord.attributes.citizen.email"),
    ]
  end
end

app/views/citizens/_form.html.erb
<%= form_for(citizen, method: citizen.new_record? ? :post : :put,
             html: { multipart: true, class: "grid", data: { controller: "citizen", turbo: false } }) do |f| %>
  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :name } %>
    <%= render partial: "components/form/inputs/text_field", locals: { f: f, name: :name, attrs: {} } %>
    <%= errors_for(f, :name) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :cpf } %>
    <%= render partial: "components/form/inputs/text_field", locals: { f: f, name: :cpf, attrs: { data: { masks_target: "cpf" } } } %>
    <%= errors_for(f, :cpf) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :birthdate } %>
    <%= render partial: "components/form/inputs/text_field", locals: { f: f, name: :birthdate, attrs: { data: { masks_target: "date" } } } %>
    <%= errors_for(f, :birthdate) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :cns } %>
    <%= render partial: "components/form/inputs/text_field", locals: { f: f, name: :cns, attrs: {} } %>
    <%= errors_for(f, :cns) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :email } %>
    <%= render partial: "components/form/inputs/email_field", locals: { f: f, name: :email, attrs: { data: { masks_target: "email" } } } %>
    <%= errors_for(f, :email) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :phone } %>
    <%= render partial: "components/form/inputs/text_field", locals: { f: f, name: :phone, attrs: { data: { masks_target: "phone" } } } %>
    <%= errors_for(f, :phone) %>
  </div>

  <%= f.fields_for :address, citizen.address || Address.new do |ff| %>
    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :zipcode } %>
      <%= render partial: "components/form/inputs/text_field", locals: { f: ff, name: :zipcode, attrs: { data: { masks_target: "zipcode" } } } %>
      <%= errors_for(ff, :zipcode) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :street } %>
      <%= render partial: "components/form/inputs/text_field", locals: { f: ff, name: :street, attrs: {} } %>
      <%= errors_for(ff, :street) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :complement } %>
      <%= render partial: "components/form/inputs/text_field", locals: { f: ff, name: :complement, attrs: {} } %>
      <%= errors_for(ff, :complement) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :neighbourhood } %>
      <%= render partial: "components/form/inputs/text_field", locals: { f: ff, name: :neighbourhood, attrs: {} } %>
      <%= errors_for(ff, :neighbourhood) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :ibge_code } %>
      <%= render partial: "components/form/inputs/text_field", locals: { f: ff, name: :ibge_code, attrs: {} } %>
      <%= errors_for(ff, :ibge_code) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :state_id } %>
      <%= render partial: "components/form/select", locals: {
        object_name: "citizen[address_attributes]",
        name: :state_id,
        collection: states,
        selected: ff.object.state_id,
        attrs: { data: { action: "change->citizen#handleStateChange" } }
      } %>
      <%= errors_for(ff, :city_id) %>
    </div>

    <div class="mb-5">
      <%= render partial: "components/form/label", locals: { f: ff, name: :city_id } %>
      <%= render partial: "components/form/select", locals: {
        object_name: "citizen[address_attributes]",
        name: :city_id,
        collection: cities,
        selected: ff.object.city_id,
        attrs: {}
      } %>
      <%= errors_for(ff, :city_id) %>
    </div>
  <% end %>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :photo } %>
    <%= render partial: "components/form/inputs/file", locals: {
      object_name: "citizen",
      name: :photo,
      attrs: {}
    } %>
    <%= errors_for(f, :photo) %>
  </div>

  <div class="mb-5">
    <%= render partial: "components/form/label", locals: { f: f, name: :active } %>
    <%= render partial: "components/form/inputs/checkbox", locals: { f: f, name: :active, attrs: {} } %>
    <%= errors_for(f, :active) %>
  </div>

  <div class="flex">
    <%= render partial: "components/form/button", locals: { f: f, name: t("actions.save"), type: "submit" } %>
  </div>
<% end %>

app/views/citizens/edit.html.erb
<div class="grid gap-10">
  <%= render "components/link", name: t("actions.back"), url: citizens_path %>
  <%= render "form", citizen: @citizen, states: @states, cities: @cities %>
</div>

app/views/citizens/index.html.erb
<div class="grid gap-10" data-controller="citizens">
  <%= form_for(:citizens, url: citizens_path, method: :get) do %>
    <%= render "components/form/inputs/search_input" %>
  <% end %>

  <div class="flex">
    <%= render partial: "components/link", locals: { name: t("actions.new"), url: new_citizen_path } %>
  </div>

  <%= render partial: "components/table", locals: { headers: headers, rows: [] } %>
</div>

app/views/citizens/new.html.erb
<div class="grid gap-10">
  <%= render "components/link", name: t("actions.back"), url: citizens_path %>
  <%= render "form", citizen: @citizen, states: @states, cities: @cities %>
</div>

app/views/citizens/show.html.erb
<div class="grid gap-10">
  <%= render "components/link", name: t("actions.back"), url: citizens_path %>

  <div class="flex gap-10 justify-between block p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.name"), content: @citizen.name } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.email"), content: @citizen.email } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.birthdate"), content: @citizen.birthdate } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.cpf"), content: @citizen.cpf } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.cns"), content: @citizen.cns } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.phone"), content: @citizen.phone } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.citizen.active"), content: @citizen.active_html } %>
    </div>
  </div>

  <div class="flex gap-10 justify-between block p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <% address =  @citizen.address %>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.zipcode"), content: address.zipcode } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.street"), content: address.street } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.complement"), content: address.complement } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.neighbourhood"), content: address.neighbourhood } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.state_id"), content: address.state } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.city_id"), content: address.city } %>
    </div>

    <div>
      <%= render partial: "components/card", locals: { title: t("activerecord.attributes.address.ibge_code"), content: address.ibge_code } %>
    </div>
  </div>

  <div class="block p-6 bg-white border border-gray-200 rounded-lg shadow hover:bg-gray-100 dark:bg-gray-800 dark:border-gray-700 dark:hover:bg-gray-700">
    <%= image_tag(@citizen.photo.url, class: "h-auto max-w-full") %>
  </div>

  <%= render "components/link", name: t("actions.edit"), url: edit_citizen_path(@citizen) %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MunicipesTest</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 grid">
      <%= render "shared/flash_messages" %>
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash_messages.html.erb
<% if flash.any? %>
  <% flash.each do |type, message| %>
    <div id="alert" class="flex items-center p-4 mb-4 rounded-lg dark:bg-gray-800 <%= color_classes(type) %>" role="alert">
      <svg class="flex-shrink-0 w-4 h-4" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M10 .5a9.5 9.5 0 1 0 9.5 9.5A9.51 9.51 0 0 0 10 .5ZM9.5 4a1.5 1.5 0 1 1 0 3 1.5 1.5 0 0 1 0-3ZM12 15H8a1 1 0 0 1 0-2h1v-3H8a1 1 0 0 1 0-2h2a1 1 0 0 1 1 1v4h1a1 1 0 0 1 0 2Z"/>
      </svg>
      <span class="sr-only">Info</span>
      <div class="ms-3 text-sm font-medium">
        <%= message %>
      </div>
    </div>
  <% end %>
<% end %>